# Generated by Django 4.1.3 on 2023-10-26 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
    ]
