# Generated by Django 4.1.3 on 2023-10-27 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_course_session"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Session",
            new_name="Session_Year",
        ),
    ]
