# Generated by Django 4.1.3 on 2023-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_staff_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
